<?php

namespace App\Services;

use App\Enums\DnaProvider;
use App\Models\DnaKit;
use App\Models\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class DnaImportService
{
    private const HEADER_LINES_TO_SCAN = 40;
    private const CHUNK_SIZE           = 8192; // bytes per fread pass when counting SNPs

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Store the uploaded raw DNA file, parse metadata, and persist a DnaKit.
     */
    public function import(User $user, UploadedFile $file, ?string $personId = null): DnaKit
    {
        $disk       = config('integrations.dna.disk', 'local');
        $prefix     = config('integrations.dna.path_prefix', 'dna-kits');
        $fileName   = Str::uuid().'_'.preg_replace('/[^a-zA-Z0-9._-]/', '_', $file->getClientOriginalName());
        $path       = "{$prefix}/{$user->id}/{$fileName}";

        Storage::disk($disk)->putFileAs(
            "{$prefix}/{$user->id}",
            $file,
            $fileName,
        );

        $headers   = $this->readHeaderLines($file->getRealPath());
        $provider  = $this->detectProvider($headers);
        $meta      = $this->extractMeta($headers, $provider);
        $snpCount  = $this->countSnps($file->getRealPath(), $provider);

        return DnaKit::create([
            'user_id'              => $user->id,
            'person_id'            => $personId,
            'provider'             => $provider,
            'kit_name'             => $meta['kit_name'] ?? $file->getClientOriginalName(),
            'file_path'            => $path,
            'snp_count'            => $snpCount,
            'haplogroup_y'         => $meta['haplogroup_y'] ?? null,
            'haplogroup_mt'        => $meta['haplogroup_mt'] ?? null,
            'ancestry_composition' => $meta['ancestry_composition'] ?? null,
            'sample_date'          => $meta['sample_date'] ?? null,
        ]);
    }

    // -------------------------------------------------------------------------
    // Format detection
    // -------------------------------------------------------------------------

    private function detectProvider(array $headerLines): DnaProvider
    {
        $header = implode("\n", $headerLines);

        return match (true) {
            str_contains($header, '23andMe')                              => DnaProvider::TwentyThreeAndMe,
            str_contains($header, 'AncestryDNA')                         => DnaProvider::AncestryDNA,
            str_contains($header, 'Family Tree DNA') ||
                str_contains($header, 'FTDNA')                           => DnaProvider::FTDNA,
            str_contains($header, 'MyHeritage')                          => DnaProvider::MyHeritage,
            str_contains($header, 'Living DNA') ||
                str_contains($header, 'LivingDNA')                       => DnaProvider::LivingDNA,
            default                                                       => DnaProvider::Other,
        };
    }

    // -------------------------------------------------------------------------
    // Metadata extraction
    // -------------------------------------------------------------------------

    /**
     * @return array<string, mixed>
     */
    private function extractMeta(array $headerLines, DnaProvider $provider): array
    {
        $meta = [];
        $header = implode("\n", $headerLines);

        // 23andMe embeds haplogroups in comment lines
        if ($provider === DnaProvider::TwentyThreeAndMe) {
            if (preg_match('/Paternal Haplogroup:\s*([^\s\n]+)/i', $header, $m)) {
                $meta['haplogroup_y'] = $m[1];
            }
            if (preg_match('/Maternal Haplogroup:\s*([^\s\n]+)/i', $header, $m)) {
                $meta['haplogroup_mt'] = $m[1];
            }
            if (preg_match('/generated by 23andMe at:\s*(.+)/i', $header, $m)) {
                $parsed = date_create(trim($m[1]));
                if ($parsed) {
                    $meta['sample_date'] = date_format($parsed, 'Y-m-d');
                }
            }
        }

        // AncestryDNA date line
        if ($provider === DnaProvider::AncestryDNA) {
            if (preg_match('/generated by AncestryDNA at:\s*(.+)/i', $header, $m)) {
                $parsed = date_create(trim($m[1]));
                if ($parsed) {
                    $meta['sample_date'] = date_format($parsed, 'Y-m-d');
                }
            }
        }

        return $meta;
    }

    // -------------------------------------------------------------------------
    // SNP counting (streaming — avoids loading entire file into memory)
    // -------------------------------------------------------------------------

    private function countSnps(string $filePath, DnaProvider $provider): int
    {
        $fh    = fopen($filePath, 'r');
        $count = 0;

        while (! feof($fh)) {
            $line = fgets($fh);
            if ($line === false) {
                break;
            }
            $trimmed = ltrim($line);
            if ($trimmed === '' || $trimmed[0] === '#') {
                continue;
            }
            // Skip header row (starts with 'rsid' or 'RSID')
            if (stripos($trimmed, 'rsid') === 0) {
                continue;
            }
            $count++;
        }

        fclose($fh);

        return $count;
    }

    /**
     * @return list<string>
     */
    private function readHeaderLines(string $filePath): array
    {
        $lines = [];
        $fh    = fopen($filePath, 'r');
        $i     = 0;

        while (! feof($fh) && $i < self::HEADER_LINES_TO_SCAN) {
            $line = fgets($fh);
            if ($line === false) {
                break;
            }
            if (ltrim($line)[0] !== '#') {
                break; // stop at first non-comment line
            }
            $lines[] = rtrim($line);
            $i++;
        }

        fclose($fh);

        return $lines;
    }
}
