<?php

namespace Tests\Feature\Api;

use App\Models\User;
use App\Support\Authorization\TreeAccessService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class DnaKitApiTest extends TestCase
{
    use RefreshDatabase;

    private function makeUser(): User
    {
        $user = User::factory()->create();
        app(TreeAccessService::class)->assignDefaultRole($user);
        Sanctum::actingAs($user);

        return $user;
    }

    private function fake23andMeFile(): UploadedFile
    {
        $content = implode("\n", [
            '# This data file generated by 23andMe at: Wed Jan 01 12:00:00 2020',
            '# Paternal Haplogroup: R-M269',
            '# Maternal Haplogroup: H1',
            "# rsid\tchromosome\tposition\tgenotype",
            "rs4477212\t1\t82154\tAA",
            "rs3094315\t1\t752566\tGG",
            "rs3131972\t1\t752721\tAG",
        ]);

        return UploadedFile::fake()->createWithContent('genome.txt', $content);
    }

    public function test_uploading_a_kit_detects_provider_and_haplogroups(): void
    {
        Storage::fake('local');
        $this->makeUser();

        $this->postJson('/api/v1/dna-kits', ['file' => $this->fake23andMeFile()])
            ->assertCreated()
            ->assertJsonPath('provider', '23andme')
            ->assertJsonPath('haplogroup_y', 'R-M269')
            ->assertJsonPath('haplogroup_mt', 'H1')
            ->assertJsonPath('snp_count', 3);

        $this->getJson('/api/v1/dna-kits')->assertOk()->assertJsonCount(1, 'data');
    }

    public function test_a_kit_can_be_renamed_and_deleted(): void
    {
        Storage::fake('local');
        $this->makeUser();

        $id = $this->postJson('/api/v1/dna-kits', ['file' => $this->fake23andMeFile()])->json('id');

        $this->patchJson("/api/v1/dna-kits/{$id}", ['kit_name' => 'Grandpa’s kit'])
            ->assertOk()->assertJsonPath('kit_name', 'Grandpa’s kit');

        $this->deleteJson("/api/v1/dna-kits/{$id}")->assertOk()->assertJsonPath('deleted', true);
        $this->getJson('/api/v1/dna-kits')->assertOk()->assertJsonCount(0, 'data');
    }

    public function test_kits_are_scoped_to_their_owner(): void
    {
        Storage::fake('local');
        $owner = $this->makeUser();
        $id = $this->postJson('/api/v1/dna-kits', ['file' => $this->fake23andMeFile()])->json('id');

        $this->makeUser(); // a different user
        $this->deleteJson("/api/v1/dna-kits/{$id}")->assertForbidden();
        $this->getJson('/api/v1/dna-kits')->assertOk()->assertJsonCount(0, 'data');
    }
}
